//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.15 at 03:10:19 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:wco:datamodel:WCO:DocumentMetaData-DMS:2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package wco.datamodel.wco.documentmetadata_dms._2;
